--SELECT GETDATE()

--SELECT YEAR(GETDATE())
--SELECT MONTH(GETDATE())
--SELECT DAY(GETDATE())

SELECT * FROM Employees E
--WHERE E.BirthDate>='1960-1-1'
--WHERE YEAR(E.BirthDate)>=1960
--WHERE MONTH(GETDATE())=MONTH(E.BirthDate)
WHERE DAY(E.HireDate)>=8